### ISSUE TITLE
YAATA SMS

### ISSUE THREAD

**Issue by ivysrono** [AmazingApps/Amazing-Android-Apps#3]
[YAATA SMS](https://play.google.com/store)
少有的能在通知栏标记任意多条短信为已读的。
Sidebar - Notifications - Advanced mode - Status bar - Actions - Swipe action / Notification buttons

BTW，借地寻能在通知栏将Gmail一键标记为已读并存档的邮箱APP。自mailbox归天，这个功能就再也没用上过。

**Comment by Riajyuu** [comment]
@ivysrono 试试 bluemail？？好像可以

**Comment by ivysrono** [comment]
#7
