### ISSUE TITLE
花哪儿记账

### ISSUE THREAD

**Issue by gloomy-ghost** [AmazingApps/Amazing-Android-Apps#9]
Play: https://play.google.com/store/apps/details?id=com.kongzue.paywhere
隐私条款: http://paywhere.cn/agreement.html
Android 绿色应用公约支持者: https://github.com/green-android/certification/issues/1

轻度试用感觉不错，简洁的记账app，支持同步和多人账单，~~不过复式记账什么的就不要指望了~~
目前比较在意的一点是同步没有TLS，因此只当单机版来用

**Comment by Riajyuu** [comment]
这么敏感的东西 同步没有安全保障 那就算了
